const prezentareNume =
    'Derzelas este un zeu dac al sănătăţii şi al vitalităţii spirituale umane, supranumit şi ”Zeul cel Mare”. Simbolistica prezenţa în denumirea asociaţiei denotă grijă asupra omului, nucleul în jurul căruia ar trebui să se contureze toate activităţile societăţii în care trăim. Conştientizând acest fapt, toată atenţia şi tot sprijinul venit din partea membrilor asociaţiei Derzelas se îndreaptă asupra persoanelor care au cu adevărat nevoie de bunăvoinţa celor din jur.';
const autorizatie1 =
    'Departamentul Persoanelor cu Dizabilități Cluj Cowork – Producție și Servicii din cadrul Asociației Derzelas, în baza ORDINULUI Nr. 1423 privind aprobarea Procedurii de autorizare a unităților protejate publicat în M.Of.Nr.1048 din 9 noiembrie 2020 de către Ministerul Muncii și Protecției Sociale, este autorizat ca Unitate Protejată având AUTORIZAȚIA DE FUNCȚIONARE CA UNITATE PROTEJATĂ nr. 91/10.03.2021.';

const autorizatie2 =
    'Departamentul Persoanelor cu Dizabilități Fabricarea de Calculatoare si Furnizarea de Servicii Informatice din cadrul Asociației Derzelas, în baza ORDINULUI Nr. 847/2021 privind aprobarea Procedurii de autorizare a unităților protejate de către Ministerul Muncii și Protecției Sociale, este autorizat ca Unitate Protejată având AUTORIZAȚIA DE FUNCȚIONARE CA UNITATE PROTEJATĂ nr. 262/18.11.2021.';
const prezentareAsociatie =
    'Prin parteneriate și colaborări, Asociația Derzelas a înființat puncte de lucru unde desfășoară activițăți de producție și prestări de servicii în vederea realizării de produse și servicii cu participarea și prin propria activitate a persoanei cu handicap angajate în cadrul unității protejate. Profitul obținut în urma comercializării produselor și prestării serviciilor vor fi utilizate exclusiv în sprijinirea persoanelor cu dizabilități, în lumina viziunii asociației, aceea de a asigura un trai ideal persoanelor cu dizabilități prin înlăturarea barierelor sociale și profesionale. Persoanele cu dizabilități angajate în cadrul Unității Protejate pentru care solicităm autorizarea sunt beneficiari ai atelierelor de terapie susținute de către Asociația Derzelas în vederea realizării misiunii noastre, incluziunea socială și profesională a persoanelor cu dizabilități în comunitate.';
const produseDescriere =
    " * Produse de birotică și papetărie personalizate, ambalaje și cutii din carton tare sau microondulat și din lemn, mape, orice produs realizat pe suport de hârtie sau lemn, etichete, agende, calendare, reclame și firme luminoase, articole pe suport de lemn sau carton realizate și pictate manual, diverse articole promoţionale, articole personalizate.​ \n * Articole confecţionate din textile, articole de îmbrăcăminte, diverse echipamente de lucru, echipamente de protecție, alte articole de îmbrăcăminte, inclusiv din piele, accesorii, orice fel de articol de îmbrăcăminte personalizat (iclusiv prin broderie), orice articole obținute prin tricotare sau croșetare.​\n * Mobilier pentru birouri, mobilier pentru spații comerciale, mobilier pentru farmacii, bancuri de lucru, mobilier pentru școli și grădinițe, scaune și bănci pentru grădină, placări și mobilier special, mobilier pentru orice spațiu ce se poate executa din plăci de PAL, plăci de MDF, fronturi MDF înfoliat, vopsit sau lemn furniruit.​\n * Fabricarea de Calculatoare​";
const serviciiDescriere =
    "Servicii de legătorie şi servicii conexe, activităţi de fotocopiere, de pregătire a documentelor în vederea arhivării şi alte activităţi specializate de secretariat.\n * Acordare consultanță, îndrumare și asistență operațională pentru firme și alte organizații pe probleme de management, planificare strategică și organizatorică, procese de retehnologizare, managementul schimbărilor, reducerea costurilor și alte probleme financiare; consultanță (inclusiv pentru accesare de fonduri europene), îndrumare sau asistență operațională pentru firme și servicii publice cu privire la proiectarea metodelor sau procedurilor contabile, servicii de BI (Business Inteligence). \n * Prelucrarea datelor, administrarea paginilor web și activități conexe incluzând asigurarea infrastructurii pentru serviciile de găzduire a paginilor web, de prelucrare a datelor și activități conexe. \n * Activități de consultanță în tehnologia informației precum planificarea și proiectarea sistemelor de calculatoare ce integrează hardware, software și tehnologii de comunicații și activitatea de pregătire a utilizatorilor. \n * Activități de studiere a pieței și de sondare a opiniei publice, de design specializat, alte activități profesionale și tehnice. \n * Servicii generale de curățenie. \n * Organizări de evenimente: organizarea de evenimente corporative, în funcție de nevoi, oferind servicii de închiriere locații cu dotări și servicii audio-video (sisteme de prezentare și afișare, videoproiector, instalații de sonorizare etc.), catering (cocktail-uri, cine festive, coffe break, recepții etc.), transport, traducere simultană, programe optionale. \n * Furnizarea de Servicii Informatice";
const activitatiPagina =
    'Programele dezvoltate de asociaţia Derzelas pentru tinerii cu dizabilităţi se bazează pe: terapie prin artă (ateliere de pictură – pictură pe sticlă, pictură pe ouă, pictură pe lemn; sculptură; ceramică; ateliere de creaţie produse artizanale- coroniţe, suport pentru lumânări, suport pentru chei, ceasuri de perete), terapie educaţională (dezvoltarea competenţelor în ceea ce priveşte stăpânirea unei limbi străine), gimnastică medicală şi de recuperare, tabere de recreere şi relaxare. Prin aceste programe asociaţia îşi propune în primul rând descoperirea unor aptitudini şi pasiuni ale persoanelor cu dizabilităţi, urmând că prin acţiunile ulterioare, aceştia să fie orientaţi şi îndrumaţi în alegerea unui mediu profesional potrivit pentru fiecare. Aceste programe dezvoltate de asociaţia Derzelas pentru tinerii cu dizabilităţi sunt doar o etapă premergătoare acţiunilor de incluziune socio-profesională pe care asociaţia le va derula. \n \n Considerăm că prin terapii specifice, persoanele cu dizabilităţi, pot găsi modalităţi de a se exprimă şi de a prezenţa experienţele lor de viaţă altora. Prin culori, prin forme, prin sunete, tinerii cu dizabilităţi exprimă emoţiile şi trăirile lor, contribuind prin această la deschiderea unor noi perspective pentru ceilalţi. Astfel, putem fi capabili să ne imaginăm şi să empatizam cu cei din jurul nostru. \n \n Derularea acestor activităţi au loc în parteneriate cu diferiţi artişti plastici, kinetoterapeuti, persoane specializate pe gimnastică medicală şi masaje de recuperare. Prin toate aceste activităţi derulate tinerii pot să îşi împărtăşească dorinţele şi să îşi materializeze gândurile, să se exprime şi să cunoască aprecierea celor din jurul lor.';
const misiuneFormatata =
    'Asociația Derzelas implementează, cu personal specializat, \n programe specifice de incluziune socio-profesională a persoanelor cu dizabilități \n și face cunoscute în rândul comunității problemele cu care acestea se confruntă.';
const prezentareNumeFormatata =
    'Derzelas este un zeu dac al sănătăţii şi al vitalităţii spirituale umane, supranumit şi ”Zeul cel Mare”.\n Simbolistica prezenţa în denumirea asociaţiei denotă grijă asupra omului, \n nucleul în jurul căruia ar trebui să se contureze toate activităţile societăţii în care trăim.';
const prezentareAsociatieFormatata =
    'Asociația Derzelas a înființat puncte de lucru unde desfășoară activițăți de producție și prestări de servicii \nîn vederea realizării de produse și servicii cu participarea și prin propria activitate \na persoanei cu handicap angajate în cadrul unității protejate.';
const misiuneViziuneObiectiveTitlu = 'Misiune, viziune, obiective';
const misiuneTitlu = 'Misiune';
const viziuneTitlu = 'Viziune';
const obiectiveTitlu = 'Obiective';
const misiuneViziuneObiectiveText =
    'În baza documentelor constitutive Asociaţia Derzelas dezvoltă o serie de activităţi şi programe pentru persoanele cu dizabilităţi din Cluj-Napoca dorind prin acestea sprijinirea acestora.\n \n Derzelas organizează ateliere de terapie prin artă, ateliere de terapie educativă, programe specifice de recuperare şi gimnastică medicală, programe de incluziune socio-profesională pentru persoanele cu dizabilităţi. Activităţile derulate vor spori încrederea şi motivaţia persoanelor cu dizabilităţi de a fi într-o continuă învăţare şi evoluţie, reuşind astfel să se formeze armonios atât la nivel individual cât şi la nivel social, colectiv.';
const misuneText =
    'Asociația Derzelas implementează, cu personal specializat, programe specifice de incluziune socio-profesională a persoanelor cu dizabilități și face cunoscute în rândul comunității problemele cu care acestea se confruntă.';
const vizuneText =
    'Asigurarea unui trai ideal persoanelor cu dizabilități prin înlăturarea barierelor sociale și profesionale';
const obiectiveText =
    'Printre obiectivele vizate de către Asociaţia Derzelas se pot enumera:\n – identificarea şi orientarea tinerilor cu dizabilităţi pentru programele de incluziune socio-profesională specifice.\n – dezvoltarea unor proiecte de conştientizare şi de mobilizare a comunităţii asupra problemelor confruntate de persoanele cu dizabilităţi.\n – participarea la diferite evenimente pentru dezvoltarea şi susţinerea persoanelor cu dizabilităţi\n – promovarea cauzei noastre de conştientizare şi sprijinire a persoanelor cu dizabilităţi.\n – organizarea unor workshop-uri având drept scop incluziunea socio-profesională a persoanelor cu dizabilităţi.\n – dezvoltarea reţelei de voluntari şi de sponsori pentru activităţile complexe viitoare.\n – intermedierea schimbului de experienţă între persoanele cu dizabilităţi din comunităţile străine şi cea română – conştientizarea comunităţii străine cu privire la problemele şi mijloacele disponibile de sprijinire a persoanelor cu dizabilităţi.\n Reuşind să implementăm o parte sau chiar toate dintre obiectivele propuse, putem facilita accesul pe piaţă muncii persoanelor cu dizabilităţi, oferindu-le astfel posibilitatea de a se integra armonios în mediul social şi profesional.';
