const prezentareNume =
    'Derzelas este un zeu dac al sănătăţii şi al vitalităţii spirituale umane, supranumit şi ”Zeul cel Mare”. Simbolistica prezenţa în denumirea asociaţiei denotă grijă asupra omului, nucleul în jurul căruia ar trebui să se contureze toate activităţile societăţii în care trăim. Conştientizând acest fapt, toată atenţia şi tot sprijinul venit din partea membrilor asociaţiei Derzelas se îndreaptă asupra persoanelor care au cu adevărat nevoie de bunăvoinţa celor din jur.';
const autorizatie1 =
    'Departamentul Persoanelor cu Dizabilități Cluj Cowork – Producție și Servicii din cadrul Asociației Derzelas, în baza ORDINULUI Nr. 1423 privind aprobarea Procedurii de autorizare a unităților protejate publicat în M.Of.Nr.1048 din 9 noiembrie 2020 de către Ministerul Muncii și Protecției Sociale, este autorizat ca Unitate Protejată având AUTORIZAȚIA DE FUNCȚIONARE CA UNITATE PROTEJATĂ nr. 91/10.03.2021.';

const autorizatie2 =
    'Departamentul Persoanelor cu Dizabilități Fabricarea de Calculatoare si Furnizarea de Servicii Informatice din cadrul Asociației Derzelas, în baza ORDINULUI Nr. 847/2021 privind aprobarea Procedurii de autorizare a unităților protejate de către Ministerul Muncii și Protecției Sociale, este autorizat ca Unitate Protejată având AUTORIZAȚIA DE FUNCȚIONARE CA UNITATE PROTEJATĂ nr. 262/18.11.2021.';
const prezentareAsociatie =
    'Prin parteneriate și colaborări, Asociația Derzelas a înființat puncte de lucru unde desfășoară activițăți de producție și prestări de servicii în vederea realizării de produse și servicii cu participarea și prin propria activitate a persoanei cu handicap angajate în cadrul unității protejate. Profitul obținut în urma comercializării produselor și prestării serviciilor vor fi utilizate exclusiv în sprijinirea persoanelor cu dizabilități, în lumina viziunii asociației, aceea de a asigura un trai ideal persoanelor cu dizabilități prin înlăturarea barierelor sociale și profesionale. Persoanele cu dizabilități angajate în cadrul Unității Protejate pentru care solicităm autorizarea sunt beneficiari ai atelierelor de terapie susținute de către Asociația Derzelas în vederea realizării misiunii noastre, incluziunea socială și profesională a persoanelor cu dizabilități în comunitate.';
const produseDescriere =
    " * Produse de birotică și papetărie personalizate, ambalaje și cutii din carton tare sau microondulat și din lemn, mape, orice produs realizat pe suport de hârtie sau lemn, etichete, agende, calendare, reclame și firme luminoase, articole pe suport de lemn sau carton realizate și pictate manual, diverse articole promoţionale, articole personalizate.​ \n * Articole confecţionate din textile, articole de îmbrăcăminte, diverse echipamente de lucru, echipamente de protecție, alte articole de îmbrăcăminte, inclusiv din piele, accesorii, orice fel de articol de îmbrăcăminte personalizat (iclusiv prin broderie), orice articole obținute prin tricotare sau croșetare.​\n * Mobilier pentru birouri, mobilier pentru spații comerciale, mobilier pentru farmacii, bancuri de lucru, mobilier pentru școli și grădinițe, scaune și bănci pentru grădină, placări și mobilier special, mobilier pentru orice spațiu ce se poate executa din plăci de PAL, plăci de MDF, fronturi MDF înfoliat, vopsit sau lemn furniruit.​\n * Fabricarea de Calculatoare​";
const serviciiDescriere =
    "Servicii de legătorie şi servicii conexe, activităţi de fotocopiere, de pregătire a documentelor în vederea arhivării şi alte activităţi specializate de secretariat.\n * Acordare consultanță, îndrumare și asistență operațională pentru firme și alte organizații pe probleme de management, planificare strategică și organizatorică, procese de retehnologizare, managementul schimbărilor, reducerea costurilor și alte probleme financiare; consultanță (inclusiv pentru accesare de fonduri europene), îndrumare sau asistență operațională pentru firme și servicii publice cu privire la proiectarea metodelor sau procedurilor contabile, servicii de BI (Business Inteligence). \n * Prelucrarea datelor, administrarea paginilor web și activități conexe incluzând asigurarea infrastructurii pentru serviciile de găzduire a paginilor web, de prelucrare a datelor și activități conexe. \n * Activități de consultanță în tehnologia informației precum planificarea și proiectarea sistemelor de calculatoare ce integrează hardware, software și tehnologii de comunicații și activitatea de pregătire a utilizatorilor. \n * Activități de studiere a pieței și de sondare a opiniei publice, de design specializat, alte activități profesionale și tehnice. \n * Servicii generale de curățenie. \n * Organizări de evenimente: organizarea de evenimente corporative, în funcție de nevoi, oferind servicii de închiriere locații cu dotări și servicii audio-video (sisteme de prezentare și afișare, videoproiector, instalații de sonorizare etc.), catering (cocktail-uri, cine festive, coffe break, recepții etc.), transport, traducere simultană, programe optionale. \n * Furnizarea de Servicii Informatice";
